### ISSUE TITLE
Can't currently "Approve" Apps , because propagation is not sharing Required Fields

### ISSUE THREAD

**Issue by rrocchio** [ucla-oarc-mobile/casa-on-rails#115]
Can't currently "Approve" Apps , because propagation is not sharing Required Fields

2 elements to this fix:

1) Add some JSON code to the CASA Payload OUT... to share the "REQUIRED" fields - so that Apps can get approved...

2) Add some code to SHARE the Reason why an App didn't get "Approved"

**Comment by alroman** [comment]
Issue seems to be from a combination of a silent validation error in the `App` model validator and an incorrect metadata mapping from `admin_contact_*` to `primary_contact_*` that triggers the validation fail.  I have not yet traced where the metadata mapping fails.

``` ruby
  validates :primary_contact_name,
    presence: true,
    length: { maximum: 255}

  validates :primary_contact_email,
    presence: true,
    length: { minimum: 6, maximum: 255}
```

Log shows a transaction rollback on validation fail.

```
  App Load (0.3ms)  SELECT  `apps`.* FROM `apps` WHERE `apps`.`casa_id` = '71' AND `apps`.`casa_originator_id` = 'c5ac61bc-d46b-4f77-a823-a6e520da2944'  ORDER BY `apps`.`id` ASC LIMIT 1
Creating a new app from an inbound payload.
   (0.1ms)  BEGIN

Contacts -  A primary contact name is required.
Contacts -  A primary contact email address is required.
Contacts -  The primary contact email must be longer than 5 characters.
   (0.1ms)  ROLLBACK
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
Redirected to http://0.0.0.0:2000/apps
Completed 302 Found in 28ms (ActiveRecord: 1.5ms)
```

**Comment by rrocchio** [comment]
Alfonso fixed this - closing this ticket
