### ISSUE TITLE
Some variables in payloads not mapping correctly

### ISSUE THREAD

**Issue by rrocchio** [ucla-oarc-mobile/casa-on-rails#118]
Some of the variables that are being published, are not coming across into the CASA on RAILS app, even though they are in the payload... 

the ones I know about are CONTACTS: Support Contact and Email

Also, under DISPLAY:  - mobile Friendly and "official" not mapping - @ctrance  - please help us a full test on this... thanks!

**Comment by ctrance** [comment]
@rrocchio - Below are the variables that did not make it into the CASA on RAILS app:
- Competencies (one word or phrase per line)(?)
- Features (one word or phrase per line)(?)
- Download Size(?)
- Supported Languages(?)
- Support Contact
- Designations
- Categories
- Licensing(?)
- Privacy Policy URL
- Session Lifetime(?)
- Cloud Vendor(?)
- Security Policy URL(?)
- Security Text(?)
- Student Data
- LTI OAuth Key(?) and OAuth Secret(?)
- WCAG 2.0 Guideline Adherence
