### ISSUE TITLE
New Designs for Web Dashboard

### ISSUE THREAD

**Issue by laurencullen** [ucla-oarc-mobile/casa-on-rails#127]
@rrocchio @uclanate @krozett Here are the new UCLA Mobile dashboard designs we discussed for https://apps.ucla.edu/mobile. This includes the default page design as well as the page design when editing the apps displaying with the ability to add, delete, move, and reset to default.

The links, buttons, and top nav bar are all #347BAD. Best font would be SF UI Text with Proxima Nova as an alternative option. The app icons are 150 x 150 px with box-shadow: 2px 2px 2px #cccccc;

All assets are located here: https://adobe.ly/2BdX0I9

If you would need anything else on it, please let me know.

![desktop](https://user-images.githubusercontent.com/13141571/33287215-da25e92e-d36c-11e7-9ae3-6a21dbb6edee.png)
![desktop edit](https://user-images.githubusercontent.com/13141571/33287220-def38024-d36c-11e7-9d30-2c3956c167b8.png)

**Comment by uclanate** [comment]
closing this for now until we get direction from Rose to do a UI overhaul.
