### ISSUE TITLE
CCLE app icon is incorrect

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#141]
The CCLE app icon on CASA does not match the one on the Apple/Play store. Please fix.
![image](https://user-images.githubusercontent.com/1034174/43970855-cbf56cea-9c83-11e8-885c-2498a8fa69b5.png)

**Comment by ctrance** [comment]
I currently cannot assign this ticket, no privilege to do so. I'm tagging @laurencullen to upload the right CCLE app icon.

**Comment by ctrance** [comment]
@laurencullen if you do not have admin access to apps.ucla.edu, please give me the app icon and I'll upload it there. Thanks!

**Comment by laurencullen** [comment]
@ctrance I uploaded the new icon: https://apps.ucla.edu/apps/13
Here is the icon so that you have it as well:
![casa-icon](https://user-images.githubusercontent.com/13141571/43975845-cced35f0-9c93-11e8-8a7e-4de5bb1def1e.png)

Please let me know if you would need anything else on it.

**Comment by ctrance** [comment]
Looks good now, thanks @laurencullen
