### ISSUE TITLE
Add packet validation on Mobile Apps form

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#157]
For enhancement please add validation on Mobile Apps form for app to app launch correct setup.
![image](https://user-images.githubusercontent.com/1034174/46428259-58df0500-c6f8-11e8-9e52-ff62648f0174.png)

**Comment by uclanate** [comment]
Am closing this issue as there are no rigid standards for package / url scheme names to validate against
