### ISSUE TITLE
Allow line breaks on hosted privacy policy

### ISSUE THREAD

**Issue by krozett** [ucla-oarc-mobile/casa-on-rails#158]
Even if you put line breaks in your privacy policy, the page just smooshes it all into one big block of text.

Production example:
https://apps.ucla.edu/apps/60/privacy

**Comment by ctrance** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/1034174/47881264-daeb4800-dde2-11e8-8d2b-fbc9a4da0ca8.png)

**Comment by ctrance** [comment]
Works with 2 lines too
![image](https://user-images.githubusercontent.com/1034174/47881345-19810280-dde3-11e8-8b8f-a67572437cde.png)

**Comment by ctrance** [comment]
Closing this, thanks @krozett!
