### ISSUE TITLE
Create a Local Ratings Input Feature - for logged in COR Users

### ISSUE THREAD

**Issue by StillSlippery** [ucla-oarc-mobile/casa-on-rails#16]
Create a Local Ratings Feature - for logged in COR Users

This will include a new function that users see once they log in.

It will say "Rate an App" in the menu

The data that needs to be collected is as follows:

The App ID
The CASA ID ( adding this so Sanje can consume)
The Local CASA App ID ( adding this - so Sanje can consume)
The Rating giving to the app:
- IDEAL:   to have it work like this: The user sees 5 grey stars, each of them is clickable. If they click any one of them, the stars to the left fill in with the Blue color that Heather designed. The ratings are 1 - 5 only. 1 - 5 ( Decimal or numeric)
- BASIC: let user select on a horizontal set of radio buttons - 1 - 5 with label of "Low Value" on the 1 and "high value" on the 5
- MINIMAL - use a vertical set of radio buttons - 1 - 5 with the labels as such:
  - Low Value
  - Some Value
  - Expected Value
  - Good Value
  - High Value

The Comment by the Professor about the app ( Extended text or Blob)
The Date and Time the app was rated
The version of the App that was rated

**Comment by rrocchio** [comment]
@ebollens  - can this work like this:  The user sees 5 grey stars, each of them is clickable.  If they click any one of them, the stars to the left fill in with the Blue color that Heather designed.  The ratings are 1 - 5 only.
