### ISSUE TITLE
Advanced tab on Submit App form shows duplicated "Short Description"

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#163]
@uclanate I see 2 "Short Description" fields on the Advanced tab of Submit an app form.

![image](https://user-images.githubusercontent.com/1034174/48283135-764a7180-e410-11e8-9b73-8b1818f6aaef.png)

There's also a "Description" field on the Basic Info tab, I guess that's the long description right?

![image](https://user-images.githubusercontent.com/1034174/48283195-a5f97980-e410-11e8-850d-9d601168eb1c.png)

**Comment by uclanate** [comment]
Yeah I may just delete both of these. I'm trying not to delete things but this seems pretty clearly unnecessary.  I'm pretty sure Haik is pulling the long description for his client so that shouldn't cause any issues.

**Comment by uclanate** [comment]
this is fixed but we can wait until the next deploy / test cycle to close.
