### ISSUE TITLE
Intro text for Web App, iOS App & Android App are missing on the App Launch tab

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#164]
@uclanate I don't see the intro text that's written on this commit "update language on submit app form WITHOUT other dev files". Maybe I misunderstood, please close this if the below UI is what's expected, thanks!
![image](https://user-images.githubusercontent.com/1034174/48283559-bf4ef580-e411-11e8-914b-90ce3e0d907a.png)

**Comment by uclanate** [comment]
This is the expected UI. Sorry for the confusing commit message!
