### ISSUE TITLE
Change error message to say "Icon" instead of "Display" can't be blank 

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#169]
@uclanate When I submit an app without its icon, the error message showing is "Display can't be blank", it should say "Icon" instead of "Display".
![image](https://user-images.githubusercontent.com/1034174/48738193-0b195000-ec05-11e8-9b2b-0d56acc20afa.png)

**Comment by uclanate** [comment]
@krozett you're going to make fun of me for this, but I'm having the darnedest time figure out how to do this. I can't figure out where the error message is getting set for this data validation. It is not using the same method that you had me do for the app launch validation... any chance you could take a quick look and point me in the right direction? This also is NOT a major issue as well so if this is some default rails thing we can just leave it.  I think the "can't be blank" part is rails default for the "presence" validation, but I'm pretty sure the "Display" part of the error message is set somewhere...

**Comment by krozett** [comment]
@uclanate You're right that the 'can't be blank' part is happening because of the presence validation. The 'Display' is referring to the tab that the field used to live on. I'm not sure how it got in there, because that's not standard Rails practice. I would look through the code that you removed when you refactored the tabs to see anything related to validation.

**Comment by uclanate** [comment]
@krozett ok well at least I'm crazy and this IS kind of a weird tricky problem...

**Comment by uclanate** [comment]
were you able to find where exactly the error dialog is getting set??

**Comment by uclanate** [comment]
ok I'm tagging as unfinished but closing this issue as non-essential

**Comment by uclanate** [comment]
@ctrance actually I fixed this too! It still says "Display" but was able to change the other part of the error message to indicate that you needed to add an App Icon.

**Comment by ctrance** [comment]
Fixed.
