### ISSUE TITLE
Edit mode does not show the app icon

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#173]
@uclanate When you edit an app, its icon does not appear on the form.
![image](https://user-images.githubusercontent.com/1034174/49609752-4e87f400-f951-11e8-8dd4-26dcc899ba1b.png)

**Comment by uclanate** [comment]
@ctrance do you happen to know if this issue was present for a long time or if this is a new thing based on recent changes? thanks

**Comment by ctrance** [comment]
@uclanate I believe this issue has been present for a long time.

**Comment by uclanate** [comment]
This should be fixed with commit `4df9915`

**Comment by ctrance** [comment]
Fixed.
