### ISSUE TITLE
App Details show "Contact" link even if there's no contact on file

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#177]
@uclanate The OPT app details shows "contact" link even if it does not have a contact on file, screenshots below:
![image](https://user-images.githubusercontent.com/1034174/54311910-d3a72880-4592-11e9-82a3-234d7224fbce.png)
![image](https://user-images.githubusercontent.com/1034174/54311927-e0c41780-4592-11e9-92d0-eecc28da5fc6.png)
![image](https://user-images.githubusercontent.com/1034174/54311952-f0dbf700-4592-11e9-8793-a0175107e3b5.png)

**Comment by uclanate** [comment]
hmmm... can you try to replicate this on a different browser?  I couldn't get this error

**Comment by uclanate** [comment]
![Screen Shot 2019-03-13 at 2 37 58 PM](https://user-images.githubusercontent.com/27777582/54316343-b88de600-459d-11e9-8ac6-8dde5df3645d.png)

**Comment by ctrance** [comment]
@uclanate It didn't have the contact before that's why. This bug only happens if you found an app that has a missing required contact, see below:

![image](https://user-images.githubusercontent.com/1034174/54317196-bf1d5d00-459f-11e9-9782-5bce892d5a7a.png)

**Comment by ctrance** [comment]
Fixed.
