### ISSUE TITLE
App Details does not show an iOS link for an iOS app

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#178]
@uclanate BruinXperience App Edited has an iOS app but the App Details section does not show "iOS", just "Android".
![image](https://user-images.githubusercontent.com/1034174/54312401-233a2400-4594-11e9-8c4e-076275c91cbd.png)
![image](https://user-images.githubusercontent.com/1034174/54312482-51b7ff00-4594-11e9-8526-de93fe5a900a.png)

**Comment by uclanate** [comment]
@ctrance the iOS link will not show up unless they have included an App ID in the launch details. That is needed to construct the URL to the App Store page.

I'm closing this issue, but creating a new issue to "Add form validation for completing both iOS launch fields"

**Comment by ctrance** [comment]
@uclanate For BruinXperience app, we only use the URL scheme to launch from the store. I copied the exact setup from CASA prod.
