### ISSUE TITLE
Add form validation for completing both iOS launch fields

### ISSUE THREAD

**Issue by uclanate** [ucla-oarc-mobile/casa-on-rails#179]

**Comment by ctrance** [comment]
@uclanate For BruinXperience app, we only use the URL scheme to launch from the store. I copied the exact setup from CASA prod.

**Comment by uclanate** [comment]
@ctrance ok thanks I'll add this. we do need both fields filled out in case they don't have the app installed, it brings them to the store.

**Comment by uclanate** [comment]
done!

**Comment by ctrance** [comment]
Fixed.
