### ISSUE TITLE
App Details show "Privacy Policy" when there's no existing policy for the app

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#181]
@uclanate If you open "Zig Map" its App Details show "Privacy Policy when there' really no policy on file. Please fix.
![image](https://user-images.githubusercontent.com/1034174/54631131-97fbdb00-4a38-11e9-9a4b-d5ea47a2a5d9.png)

**Comment by uclanate** [comment]
done. (wait until we test on staging to close...)

**Comment by ctrance** [comment]
Fixed.
