### ISSUE TITLE
Duplicate Alt Text and Link Text

### ISSUE THREAD

**Issue by pburkeucla** [ucla-oarc-mobile/casa-on-rails#2]
For items listed in the various collection blocks:

Graphics have alt text which is the same as the text of the immediately following link. Thus:

"Graphic: CA Cultures; link: CA Cultures"

In these cases, the alt on the graphic should be null.: alt=""

**Comment by ebollens** [comment]
One of the problems in the ill-defined semantic struggles of `figcaption` versus `alt` text.
