### ISSUE TITLE
Fix Shibboleth login

### ISSUE THREAD

**Issue by krozett** [ucla-oarc-mobile/casa-on-rails#219]
- Make sure logging in to an old account still works (and the user info is the same).
- Make sure new accounts also work.

Ask me if you need me to remove any old accounts for testing.

**Comment by ctrance** [comment]
@krozett I'm getting the error message below when launching apps.ucla.edu
![image](https://user-images.githubusercontent.com/1034174/108406100-c2cbac80-71d6-11eb-8921-87f046a5f38b.png)

**Comment by ctrance** [comment]
Shibboleth login is now fixed on casa-staging.m.ucla.edu. The prod is also no longer showing the error message reported earlier.
