### ISSUE TITLE
Quick fix: change "Featured: Remote Learning Tools" to "Featured"

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#221]
@krozett On the app's new and edit page, please change "Featured: Remote Learning Tools" to "Featured" on the Categories list.
![image](https://user-images.githubusercontent.com/1034174/115600437-8decdc00-a291-11eb-8722-f51f539671ed.png)

**Comment by krozett** [comment]
I made the change on production. See #222, and you can verify it already works on staging/prod.

**Comment by ctrance** [comment]
Fixed.
