### ISSUE TITLE
Permanent fix: Make the app's categories list data driven by site settings' categories

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#222]
@krozett The categories listed in the Admin > Site Settings should drive what is listed in the new/edit app's categories list.
![image](https://user-images.githubusercontent.com/1034174/115600915-08b5f700-a292-11eb-8bfb-6abf22355dc7.png)

**Comment by krozett** [comment]
It turns out this can be done. It is already data-driven. Go to Admin > Categories, and you can edit the category name. Then edit the "Categories on Homepage" text field to match the category you just updated.

**Comment by ctrance** [comment]
Confirming that this feature already exists in staging. Basically the Admin > Categories, is where the actual category name is being managed while Admin > Site Settings > Categories manages the order on the home page. Closing this.
