### ISSUE TITLE
Categories show up - ABOVE Header line on CASA-Berkeley & CASA-UCSD

### ISSUE THREAD

**Issue by rrocchio** [ucla-oarc-mobile/casa-on-rails#39]
Categories show up - ABOVE Header line on CASA-Berkeley & CASA-UCSD
- Hoping that this is a quick fix 
  - NOTE - the UCLA CASA app store - this Doesn't happen!

**Comment by rrocchio** [comment]
@ebollens  - The Categories on http://casa-ucsd.m.ucla.edu and http://casa-berkeley.m.ucla.edu are still showing up at the top, I thought we had this fixed, or am I remembering incorrectly?

**Comment by rrocchio** [comment]
11/24 - JS and RR could not replicate... might be fixed?

**Comment by jshslsky** [comment]
This seems to only occur when the user is not logged in.
