### ISSUE TITLE
Change out the Thin webserver for a Different web server

### ISSUE THREAD

**Issue by rrocchio** [ucla-oarc-mobile/casa-on-rails#44]
Change out the Thin webserver for Passenger

**Comment by StillSlippery** [comment]
@StillSlippery

**Comment by jshslsky** [comment]
@stevenolen is this nginx?

**Comment by stevenolen** [comment]
nope thin is like webrick (the default rails server). other options are [unicorn](http://unicorn.bogomips.org/), [puma](http://puma.io/), etc.

**Comment by jshslsky** [comment]
Please see https://github.com/ucla/chef-casa-on-rails-cookbook/commit/0e7acc7ed6d5aa5e79d50f262131bf98af698f6c for the temporary fix.
