### ISSUE TITLE
redundant queued / pending apps in admin tab

### ISSUE THREAD

**Issue by jshslsky** [ucla-oarc-mobile/casa-on-rails#53]
In the admin pending apps list there can be multiple entries for the same app (same CASA identifier) from the same sender. The copies should not be displayed. 

There is also a case where the same app is shown as pending where there are different senders, but in this case the store admin can filter them out manually.

**Comment by ctrance** [comment]
@alroman @StillSlippery @rrocchio - This issue still persists on demo, see app "Badgr" from sender EduAppCenter CASA

![capture](https://cloud.githubusercontent.com/assets/1034174/18068359/ca85cc24-6df5-11e6-985b-b7643c0e4d72.PNG)
