### ISSUE TITLE
config/environments/production results in css/js-free app

### ISSUE THREAD

**Issue by stevenolen** [ucla-oarc-mobile/casa-on-rails#64]
This file isn't consistent with the version in production, namely:

in repo:

``` ruby
  config.serve_static_assets = false
  config.assets.js_compressor = :uglifier
  config.assets.compile = false
  config.assets.digest = true
```

on production server:

``` ruby
  config.serve_static_assets = true
  config.assets.digest = true
  config.assets.version = '1.0'
```

**Comment by jshslsky** [comment]
So the app works because Chef is overriding the values with its own copy of production.rb?

**Comment by stevenolen** [comment]
It's been working in production because of that, yes.  I dont think there's anything particularly wrong with a particular deploy running it's own custom environment (that's what config/environments is for, eh?) but the current production.rb file in the repo results in an unstyled/no js app being served, so these default params should probably be updated to reflect our current prod environment :)

**Comment by jshslsky** [comment]
Custom environments are :+1:, but when they are called `production` it is jarring to see inconsistencies. In this case, it means we currently have a hard dependency on an external tool to get a styled / scripted "production" environment app running. It'd be nicer to be able to grab only this repo and get up and running correctly with sensible defaults.

**Comment by stevenolen** [comment]
> it means we currently have a hard dependency on an external tool to get a styled / scripted "production" environment app running

which I think is definitely a bug/unintended.  want me to submit a pr to make these changes to the production.rb file or you'll do it?

**Comment by jshslsky** [comment]
Feel free to PR!
