### ISSUE TITLE
warning: already initialized constant OpenSSL::SSL:VerifyPeer

### ISSUE THREAD

**Issue by stevenolen** [ucla-oarc-mobile/casa-on-rails#66]
this error throws on init:

`/var/casa/config/initializers/openssl.rb:3: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER`

**Comment by jshslsky** [comment]
e02066987701a76eab3c5ac31ea0c69b79fae9a5

**Comment by azimidev** [comment]
This should fix it
```
gem uninstall openssl -v 2.0.3
gem install openssl -v 2.0.2
```
