### ISSUE TITLE
Design a spotlight section above the apps areas so that the space can be utilized optionally

### ISSUE THREAD

**Issue by rrocchio** [ucla-oarc-mobile/casa-on-rails#76]
Design a 3 rectangle ( or something like it) rotating spotlight above the top category, in the area that was originally planned for by UCLA Communications.

The Original design by UCLA Communications is here:
![spotlight - original design](https://cloud.githubusercontent.com/assets/718820/11317449/5913312a-8fe4-11e5-9599-3e50e8311cea.JPG)

It should function similar to the one on one.iu.edu  
![rotating rectangle spotlight](https://cloud.githubusercontent.com/assets/718820/11317447/0d5770b6-8fe4-11e5-84dc-11e226e864fc.JPG)

**Comment by laurencullen** [comment]
@rrocchio @joshuaselsky Here are two variations with the spotlight. Inspired by tiles on both Google Play and iTunes store. Both Google Play and iTunes feature six tiles total - we had discussed five tiles total.

Please let me know any feedback!

![casa homepage black](https://cloud.githubusercontent.com/assets/13141571/11382435/b88e95b6-92b6-11e5-9446-a2171e601d63.jpg)
![casa homepage blue](https://cloud.githubusercontent.com/assets/13141571/11382434/b88e0f10-92b6-11e5-8d81-bf163706e7f5.jpg)
