### ISSUE TITLE
Design the interface to upload the images for the rotating spotlight into the "Site Settings"

### ISSUE THREAD

**Issue by rrocchio** [ucla-oarc-mobile/casa-on-rails#78]
Design the interface to upload the images for the rotating spotlight into the "Site Settings"...

**Comment by jshslsky** [comment]
There are a few things to do here:
1. On the admin Site Settings page, there should be an "enable carousel" feature.
2. On the admin Site Settings page, there needs to be a way to upload the carousel content based on the design (e.g., header text, sub-header text, and background image).

The addition of the carousel to the home page is #76.
