### ISSUE TITLE
Bug with Proxy Handling

### ISSUE THREAD

**Issue by StillSlippery** [ucla-oarc-mobile/casa-on-rails#9]
ight now, when we're running CASA on Rails multiple time on the same host, and using Nginx to route properly, we're hitting the following error when trying to access /casa/out/payloads:

F, [2015-04-06T16:20:45.332355 #9188] FATAL -- : 
IPAddr::InvalidAddressError (invalid address):
  app/controllers/casa/out_controller.rb:15:in `new'
  app/controllers/casa/out_controller.rb:15:in`block (2 levels) in class:OutController'
  app/controllers/casa/out_controller.rb:13:in `each'
  app/controllers/casa/out_controller.rb:13:in`block in class:OutController'

This has to do with Nginx mangling the requestor address as it passes through the reverse proxy.

Refers to: https://github.com/ucla/casa-on-rails-historical/issues/50

**Comment by rrocchio** [comment]
Per our conversation over text on Friday - hoping that this is a 2 hour task

**Comment by ebollens** [comment]
I think I just got this fixed. Time will tell in like half an hour if I'm right.

**Comment by rrocchio** [comment]
@ebollens  - great news!
