### ISSUE TITLE
some images being loaded over http instead of https

### ISSUE THREAD

**Issue by stevenolen** [ucla-oarc-mobile/casa-on-rails#96]
<img width="1421" alt="screen shot 2016-03-23 at 11 37 45 am" src="https://cloud.githubusercontent.com/assets/808870/13996599/c85d6cc2-f0eb-11e5-8157-54c875d4f1b3.png">

**Comment by jshslsky** [comment]
The warning in the original comment to this issue was raised because there was an app configured to hotlink its icon. The ability to hotlink an icon was removed in the last deploy so I just updated to a locally stored icon.
